### ISSUE TITLE
Reproducible Build for 5.42.86 failed

### ISSUE THREAD

**Issue by IzzySoft** [IAEAOrg/IsotopeBrowser#6]
It looks like you've built the APK from a "dirty" working directory:

```diff
  -rw-r--r--  0.0 unx  8196972 b-  3046268 defN 1981-01-01 01:01:02 f57d1437 classes.dex
- -rw-r--r--  0.0 unx  6819840 b-  2898363 defN 1981-01-01 01:01:02 639460ca assets/nuclides.db
  -rw-r--r--  0.0 unx 13016124 b-  2174712 defN 1981-01-01 01:01:02 ae4a0092 assets/nuclides.sql
```

Guess that `nuclides.db` is not supposed to be part of the APK, is it? It also causes the APK to be about 3 MB (50%) bigger than needed :wink:

For background: At IzzyOnDroid (where [your app is listed](https://apt.izzysoft.de/packages/iaea.nds.nuclides) – be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there, so the Google Play badge does not feel so lonely) we support [Reproducible Builds](https://reproducible-builds.org/) (also see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)), and your app is set up as such. Previous releases reproduced fine – just this DB file sneaked in this time to cause a little trouble :wink:

**Comment by IzzySoft** [comment]
PS: Funny, looking at your releases, previous APKs also had the "bigger" size. Now I wonder why the build here does NOT contain the database, rather than why yours does. I wanted to compare the commits at the releases, but now I wonder even more: where did [the previous tag go to](https://github.com/IAEAOrg/IsotopeBrowser/tree/v5.42.85), that it "does not belong to any branch on this repository"? It was there when the builder here processed the release for RB.

And the riddles answer: `nuclides.db` was removed from the repo with the last commit, but must have been in your build tree when you created the APK. So I've tried a

    git restore --source=7bc0e8be07ac4c7b0f6f558ad4ea16cfc0fa7348 app/src/main/assets/nuclides.db

prior to the build here (restoring the file as it was before its removal) – but as expected, the DB file was included now but not identical to yours. Maybe you add the correct one back? :wink:

**Comment by IzzySoft** [comment]
@mverpelli I will have to commit the failed build now, as it seems we cannot fix it in timely manner – so the current release will show "RB failed" [in the repo](https://apt.izzysoft.de/packages/iaea.nds.nuclides). Hopefully, we can get this fixed for the next release then. Looking forward to your help, and thanks in advance!

**Comment by mverpelli** [comment]
@IzzySoft Thank you very much for having spotted the issue, done the forensic, and suggested the solution.
I hope I have made the fix with this new commit/release. 
Thanks again

**Comment by IzzySoft** [comment]
Thanks for fixing! I can hereby confirm the new release is RB:

```
--- END BUILD LOG ---
Keeping 'b5f0bbbc7855808bd383a6329bdd73a0d3bdaba2d7dd4495c0b11e23367115f9-iaea.nds.nuclides-v5.42.86b-upstream.apk'...
Keeping '5fcd54254dc7b89fe735f0cc7320e0e3a81017ee5bb2e00e8a67410e0b6904f8-iaea.nds.nuclides-v5.42.86b-unsigned.apk'...
Reproducible: True
Tags built: 1.
```

So the green shield will be up again with the next sync around 7 pm UTC.

**Comment by IzzySoft** [comment]
Err, wait: Did you replace the existing tag?

```
$ iod repo get iaea.nds.nuclides
iaea.nds.nuclides: looking for 'https://api.github.com/repos/IAEAOrg/IsotopeBrowser/releases'
iaea.nds.nuclides: checking tag 'v5.42.86b'
iaea.nds.nuclides: lastRelNo set to 'v5.42.86b', checking for files
iaea.nds.nuclides: Upstream file date (2024-12-05 10:37) is newer than ours (2024-12-03 19:39).
iaea.nds.nuclides: returning ['v5.42.86b','https://github.com/IAEAOrg/IsotopeBrowser/releases/download/v5.42.86b/Nuclides_x.V156_5.42.86b.apk',1733391450]
iaea.nds.nuclides: 5.42.86 up-to-date.
```

Then I have to take back my note about the green shield: as that tag was already fetched to the repo, the replacement won't make it (beside the fact that `*b` would stand for a "beta" which would precede the one without `*b`, the APK has the very same `versionCode` as the previous one, so I cannot even pull it in manually: having the same `versionCode` it would not reach those who already updated to the previous APK, as Android uses `versionCode` to tell if something is an update). So, shield won't be up with the next sync – but hopefully will be up with the next release then.

Friendly hint for future releases: Never replace what was already distributed, dragons (and nasty side-effects) there :dragon: :wink:

**Comment by mverpelli** [comment]
Sorry for taking your time on troubleshooting, I will increase the `versionCode`, and the tag as well, and thank you for being friendly 😉

**Comment by IzzySoft** [comment]
Thanks again for your help! Guess this issue can be closed again then?
